"""Excel bulk-upload parsing for Customers and Sales, off app-provided
templates (not a specific vendor's own format, unlike purchase_import.py).
Both templates are generated by this module too, so the columns here and
the columns in the downloadable template can never drift apart.

Same header-name-driven, fail-loudly philosophy as purchase_import.py and
gst_logic.py's GSTR-2B parser: scans for the expected column headers by
text (case-insensitive, tolerant of minor rewording) rather than fixed
cell positions, and returns a clear error message rather than guessing on
an unrecognized layout.
"""
import re
import io


CUSTOMER_HEADERS = {
    "customer_name": ["customer name", "name"],
    "contact_person": ["contact person", "contact"],
    "phone": ["phone", "mobile"],
    "email": ["email"],
    "address": ["address"],
    "gstin": ["gstin"],
    "state": ["state"],
    "state_code": ["state code"],
    "credit_limit": ["credit limit"],
    "credit_days": ["credit days"],
}

SALES_HEADERS = {
    "invoice_number": ["invoice number", "invoice #", "invoice no", "order number", "order #"],
    "date": ["date"],
    "customer_name": ["customer name", "customer"],
    "product": ["product", "product name", "item"],
    "qty": ["qty", "quantity"],
    "rate": ["rate", "unit price", "price"],
    "payment_status": ["payment status"],
    "amount_received": ["amount received"],
}


def _find_header_row(ws, required_headers, header_map, max_scan_rows=5):
    max_row = min(max_scan_rows, ws.max_row or 0)
    max_col = ws.max_column or 0
    for r in range(1, max_row + 1):
        values = {}
        for c in range(1, max_col + 1):
            v = ws.cell(row=r, column=c).value
            if isinstance(v, str) and v.strip():
                values[c] = v.strip().lower()
        if not values:
            continue
        found = {}
        for key, aliases in header_map.items():
            for c, v in values.items():
                if any(a in v for a in aliases):
                    found[key] = c
                    break
        if all(k in found for k in required_headers):
            return r, found
    return None, {}


def _to_float(value, default=0.0):
    if value is None:
        return default
    if isinstance(value, (int, float)):
        return float(value)
    s = str(value).strip()
    if not s:
        return default
    try:
        return float(s)
    except ValueError:
        s = re.sub(r"[^0-9.\-]", "", s)
        return float(s) if s else default


def _to_int(value, default=0):
    return int(_to_float(value, default))


def _to_date_str(value):
    import datetime as _dt
    if isinstance(value, _dt.datetime):
        return value.date().isoformat()
    if isinstance(value, _dt.date):
        return value.isoformat()
    s = str(value or "").strip()
    if not s:
        return ""
    m = re.match(r"^(\d{4})[/-](\d{1,2})[/-](\d{1,2})$", s)
    if m:
        y, mo, d = m.groups()
        return f"{int(y):04d}-{int(mo):02d}-{int(d):02d}"
    m = re.match(r"^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$", s)
    if m:
        d, mo, y = m.groups()
        return f"{int(y):04d}-{int(mo):02d}-{int(d):02d}"
    return s


def _open_first_sheet(file_path):
    import openpyxl
    wb = openpyxl.load_workbook(file_path, data_only=True, read_only=True)
    ws = wb[wb.sheetnames[0]]
    return wb, ws


def parse_customers_excel(file_path):
    """Returns {ok, message, rows} where rows is a list of dicts:
    {customer_name, contact_person, phone, email, address, gstin, state,
     state_code, credit_limit, credit_days}. Only customer_name is
     required per row - blank rows (no name) are skipped."""
    try:
        wb, ws = _open_first_sheet(file_path)
    except Exception as e:
        return dict(ok=False, message=f"Could not open this as an Excel (.xlsx) file: {e}", rows=[])

    try:
        header_row, cols = _find_header_row(ws, ["customer_name"], CUSTOMER_HEADERS)
        if not header_row:
            return dict(ok=False,
                        message="Couldn't find a header row with a 'Customer Name' column. Use the downloadable "
                                "template so the column headers match what this expects.",
                        rows=[])
        rows = []
        for r in range(header_row + 1, (ws.max_row or header_row) + 1):
            def cell(key):
                c = cols.get(key)
                return ws.cell(row=r, column=c).value if c else None

            name = cell("customer_name")
            if name is None or str(name).strip() == "":
                continue
            rows.append(dict(
                customer_name=str(name).strip(),
                contact_person=str(cell("contact_person") or "").strip(),
                phone=str(cell("phone") or "").strip(),
                email=str(cell("email") or "").strip(),
                address=str(cell("address") or "").strip(),
                gstin=str(cell("gstin") or "").strip(),
                state=str(cell("state") or "").strip(),
                state_code=str(cell("state_code") or "").strip(),
                credit_limit=_to_float(cell("credit_limit")),
                credit_days=_to_int(cell("credit_days")),
            ))
    finally:
        wb.close()

    if not rows:
        return dict(ok=False, message="Found a header row but no data rows under it.", rows=[])
    return dict(ok=True, message=f"Parsed {len(rows)} customer row(s).", rows=rows)


def parse_sales_excel(file_path):
    """Returns {ok, message, rows} where rows is a list of dicts:
    {invoice_number, date, customer_name, product, qty, rate,
     payment_status, amount_received}. Rows with no product or zero qty
     are skipped. invoice_number may be blank (each blank-invoice row
     becomes its own single-line sale on confirm)."""
    try:
        wb, ws = _open_first_sheet(file_path)
    except Exception as e:
        return dict(ok=False, message=f"Could not open this as an Excel (.xlsx) file: {e}", rows=[])

    try:
        header_row, cols = _find_header_row(ws, ["customer_name", "product", "qty"], SALES_HEADERS)
        if not header_row:
            return dict(ok=False,
                        message="Couldn't find a header row with 'Customer Name', 'Product', and 'Qty' columns. "
                                "Use the downloadable template so the column headers match what this expects.",
                        rows=[])
        rows = []
        for r in range(header_row + 1, (ws.max_row or header_row) + 1):
            def cell(key):
                c = cols.get(key)
                return ws.cell(row=r, column=c).value if c else None

            product = cell("product")
            qty = _to_float(cell("qty"))
            if product is None or str(product).strip() == "" or qty <= 0:
                continue
            rows.append(dict(
                invoice_number=str(cell("invoice_number") or "").strip(),
                date=_to_date_str(cell("date")),
                customer_name=str(cell("customer_name") or "").strip(),
                product=str(product).strip(),
                qty=qty,
                rate=_to_float(cell("rate")),
                payment_status=str(cell("payment_status") or "").strip() or "Unpaid",
                amount_received=_to_float(cell("amount_received")),
            ))
    finally:
        wb.close()

    if not rows:
        return dict(ok=False, message="Found a header row but no usable data rows under it "
                                       "(each row needs a Product and a Qty greater than 0).", rows=[])
    return dict(ok=True, message=f"Parsed {len(rows)} sales line(s).", rows=rows)


def build_customer_template():
    """Returns an in-memory .xlsx (BytesIO) with the Customer upload
    template: header row + one example row, plus a short instructions
    row above it."""
    import openpyxl
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Customers"
    headers = ["Customer Name", "Contact Person", "Phone", "Email", "Address", "GSTIN", "State", "State Code",
               "Credit Limit", "Credit Days"]
    ws.append(headers)
    ws.append(["ABC Traders", "Ramesh Kumar", "9876543210", "abc@example.com", "12 MG Road, Pune",
                "27ABCDE1234F1Z5", "Maharashtra", "27", 50000, 30])
    for col_idx in range(1, len(headers) + 1):
        ws.column_dimensions[chr(64 + col_idx)].width = 18
    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf


def build_sales_template():
    """Returns an in-memory .xlsx (BytesIO) with the Sales upload
    template. Rows sharing the same Invoice Number become one multi-line
    Sale on upload; leave Invoice Number blank for a single-line sale."""
    import openpyxl
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Sales"
    headers = ["Invoice Number", "Date", "Customer Name", "Product", "Qty", "Rate", "Payment Status",
               "Amount Received"]
    ws.append(headers)
    ws.append(["SO-1001", "2026-08-01", "ABC Traders", "Widget", 10, 100, "Unpaid", 0])
    ws.append(["SO-1001", "2026-08-01", "ABC Traders", "Gadget", 5, 60, "Unpaid", 0])
    for col_idx in range(1, len(headers) + 1):
        ws.column_dimensions[chr(64 + col_idx)].width = 18
    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf
