"""GST Filing business logic: due-date computation, GSTR-1/GSTR-3B
reference summaries computed from Sales/Purchases, and GSTR-2B Excel
parsing. Kept separate from app.py the same way invoice_pdf.py is, since
this is a self-contained chunk of domain logic rather than routing.

IMPORTANT — read this before trusting any date or figure this module
produces:
  - Due dates and filing rules are set by the Government of India and can
    change by notification at any time. The schedule computed here (11th/
    13th for GSTR-1, 20th/22nd/24th for GSTR-3B, 14th for GSTR-2B, 25th
    for PMT-06, and the Category X/Y state grouping for QRMP) reflects
    publicly published GST due-date calendars as of when this feature was
    built. Always confirm the actual due date on the GST portal
    (services.gst.gov.in) before relying on it.
  - The GSTR-1/GSTR-3B figures here are a REFERENCE computed from what's
    recorded in this app (Sales/Purchases) - they are not fetched from,
    and not submitted to, the GST portal. Use them as a working paper to
    cross-check against what you actually file, not as a filing itself.
  - This is not a substitute for professional tax advice.
"""
import calendar
from datetime import date

import db

MONTH_NAMES = ["", "January", "February", "March", "April", "May", "June",
               "July", "August", "September", "October", "November", "December"]

# QRMP state category (CBIC Notification 84/2020-CT and successors):
# Category X files quarterly GSTR-3B by the 22nd, Category Y by the 24th,
# of the month after the quarter ends. Codes match the INDIAN_STATES list
# in app.py (2-digit GST state codes).
CATEGORY_X_STATES = {
    "22", "23", "24", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37",
}


def add_months(d, n):
    m = d.month - 1 + n
    y = d.year + m // 12
    m = m % 12 + 1
    day = min(d.day, calendar.monthrange(y, m)[1])
    return date(y, m, day)


def period_label(year, month):
    return f"{year:04d}-{month:02d}"


def month_bounds(year, month):
    start = date(year, month, 1).isoformat()
    end = date(year, month, calendar.monthrange(year, month)[1]).isoformat()
    return start, end


def quarter_of_month(month):
    return (month - 1) // 3 + 1


# ---------------------------------------------------------------------
# Due dates
# ---------------------------------------------------------------------

def gst_due_dates(company, today=None):
    """Returns due-date items covering last/current/next period (or
    quarter, under QRMP), sorted by due date. Each item is a dict:
      {return_type, period, due_date (date object), description}
    """
    today = today or date.today()
    scheme = (company["GstFilingScheme"] or "Monthly") if company else "Monthly"
    state_code = (company["StateCode"] or "") if company else ""
    category_x = state_code in CATEGORY_X_STATES

    items = []

    # GSTR-2B: auto-generated on the 14th of the month after each return
    # period, for every taxpayer. Shown monthly regardless of scheme —
    # under QRMP the statement is cumulative for the quarter by the time
    # the quarter's 3rd month posts, but checking on the 14th each month
    # is still the right habit, so we surface it every month.
    for offset in range(-1, 2):
        d = add_months(today.replace(day=1), offset)
        due = add_months(d, 1).replace(day=14)
        items.append(dict(return_type="GSTR-2B", period=period_label(d.year, d.month), due_date=due,
                           description=f"GSTR-2B for {MONTH_NAMES[d.month]} {d.year} auto-generated by GSTN "
                                       f"(check/download it — nothing to file)"))

    if scheme == "QRMP":
        seen_quarters = set()
        for offset in range(-1, 2):
            ref = add_months(today.replace(day=1), offset * 3)
            q = quarter_of_month(ref.month)
            qend_month = q * 3
            qend_year = ref.year
            qkey = (qend_year, q)
            if qkey in seen_quarters:
                continue
            seen_quarters.add(qkey)
            q_start_month = qend_month - 2
            plabel = f"{qend_year:04d}-Q{q}"
            due_month_date = date(qend_year, qend_month, 1)
            gstr1_due = add_months(due_month_date, 1).replace(day=13)
            gstr3b_due = add_months(due_month_date, 1).replace(day=22 if category_x else 24)
            items.append(dict(return_type="GSTR-1 (Quarterly/IFF)", period=plabel, due_date=gstr1_due,
                               description=f"Quarterly GSTR-1 for Q{q} {qend_year} "
                                           f"({MONTH_NAMES[q_start_month]}-{MONTH_NAMES[qend_month]})"))
            items.append(dict(return_type="GSTR-3B (Quarterly)", period=plabel, due_date=gstr3b_due,
                               description=f"Quarterly GSTR-3B for Q{q} {qend_year} — "
                                           f"Category {'X' if category_x else 'Y'} state "
                                           f"(due {'22nd' if category_x else '24th'})"))
            for mi in (q_start_month, q_start_month + 1):
                md = date(qend_year, mi, 1)
                pmt_due = add_months(md, 1).replace(day=25)
                items.append(dict(return_type="PMT-06", period=period_label(qend_year, mi), due_date=pmt_due,
                                   description=f"Monthly tax payment (PMT-06) for {MONTH_NAMES[mi]} {qend_year}"))
    else:
        for offset in range(-1, 2):
            d = add_months(today.replace(day=1), offset)
            gstr1_due = add_months(d, 1).replace(day=11)
            gstr3b_due = add_months(d, 1).replace(day=20)
            items.append(dict(return_type="GSTR-1", period=period_label(d.year, d.month), due_date=gstr1_due,
                               description=f"Monthly GSTR-1 for {MONTH_NAMES[d.month]} {d.year}"))
            items.append(dict(return_type="GSTR-3B", period=period_label(d.year, d.month), due_date=gstr3b_due,
                               description=f"Monthly GSTR-3B for {MONTH_NAMES[d.month]} {d.year}"))

    items.sort(key=lambda x: x["due_date"])
    return items


def upcoming_due_dates(company, days_ahead=14, today=None):
    today = today or date.today()
    all_items = gst_due_dates(company, today=today)
    from datetime import timedelta
    cutoff = today + timedelta(days=days_ahead)
    return [i for i in all_items if today <= i["due_date"] <= cutoff]


# ---------------------------------------------------------------------
# GSTR-1 reference summary (from Sales / SalesLines)
# ---------------------------------------------------------------------

def gstr1_summary(year, month):
    start, end = month_bounds(year, month)
    sales = db.query("""SELECT s.*, c.CustomerName, c.GSTIN AS CustomerGSTIN FROM Sales s
                      JOIN Customers c ON c.CustomerID = s.CustomerID
                      WHERE s.SaleDate >= ? AND s.SaleDate <= ? AND s.Status <> 'Cancelled'
                      ORDER BY s.SaleDate, s.SaleID""", (start, end))

    b2b_taxable = b2b_tax = b2c_taxable = b2c_tax = 0.0
    invoices = []
    for s in sales:
        tax = (s["CGSTAmount"] or 0) + (s["SGSTAmount"] or 0) + (s["IGSTAmount"] or 0)
        is_b2b = bool(s["CustomerGSTIN"])
        if is_b2b:
            b2b_taxable += s["TaxableAmount"] or 0
            b2b_tax += tax
        else:
            b2c_taxable += s["TaxableAmount"] or 0
            b2c_tax += tax
        invoices.append(dict(sale=s, is_b2b=is_b2b, tax=round(tax, 2)))

    lines = db.query("""SELECT sl.* FROM SalesLines sl
                      JOIN Sales s ON s.SaleID = sl.SaleID
                      WHERE s.SaleDate >= ? AND s.SaleDate <= ? AND s.Status <> 'Cancelled'""", (start, end))
    by_rate = {}
    by_hsn = {}
    for l in lines:
        rate = l["GSTRate"] or 0
        r = by_rate.setdefault(rate, dict(rate=rate, taxable=0.0, cgst=0.0, sgst=0.0, igst=0.0))
        r["taxable"] += l["TaxableValue"] or 0
        r["cgst"] += l["CGSTAmount"] or 0
        r["sgst"] += l["SGSTAmount"] or 0
        r["igst"] += l["IGSTAmount"] or 0

        hsn = l["HSNCode"] or "(no HSN set)"
        h = by_hsn.setdefault(hsn, dict(hsn=hsn, qty=0.0, taxable=0.0, tax=0.0))
        h["qty"] += l["Qty"] or 0
        h["taxable"] += l["TaxableValue"] or 0
        h["tax"] += (l["CGSTAmount"] or 0) + (l["SGSTAmount"] or 0) + (l["IGSTAmount"] or 0)

    for r in by_rate.values():
        for k in ("taxable", "cgst", "sgst", "igst"):
            r[k] = round(r[k], 2)
    for h in by_hsn.values():
        for k in ("qty", "taxable", "tax"):
            h[k] = round(h[k], 2)

    total_taxable = round(b2b_taxable + b2c_taxable, 2)
    total_tax = round(b2b_tax + b2c_tax, 2)
    return dict(
        period=period_label(year, month), invoices=invoices, invoice_count=len(sales),
        b2b_taxable=round(b2b_taxable, 2), b2b_tax=round(b2b_tax, 2),
        b2c_taxable=round(b2c_taxable, 2), b2c_tax=round(b2c_tax, 2),
        total_taxable=total_taxable, total_tax=total_tax,
        total_value=round(total_taxable + total_tax, 2),
        by_rate=sorted(by_rate.values(), key=lambda x: x["rate"]),
        by_hsn=sorted(by_hsn.values(), key=lambda x: x["hsn"]),
    )


# ---------------------------------------------------------------------
# GSTR-3B reference summary (Table 3.1 outward + Table 4 ITC + net payable)
# ---------------------------------------------------------------------

def gstr3b_summary(year, month):
    start, end = month_bounds(year, month)
    period = period_label(year, month)

    sales_agg = db.query("""SELECT COALESCE(SUM(TaxableAmount),0) AS taxable,
                          COALESCE(SUM(CGSTAmount),0) AS cgst, COALESCE(SUM(SGSTAmount),0) AS sgst,
                          COALESCE(SUM(IGSTAmount),0) AS igst
                          FROM Sales WHERE SaleDate >= ? AND SaleDate <= ? AND Status <> 'Cancelled'""",
                          (start, end), one=True)
    purch_agg = db.query("""SELECT COALESCE(SUM(TaxableAmount),0) AS taxable,
                          COALESCE(SUM(CGSTAmount),0) AS cgst, COALESCE(SUM(SGSTAmount),0) AS sgst,
                          COALESCE(SUM(IGSTAmount),0) AS igst
                          FROM Purchases WHERE PurchaseDate >= ? AND PurchaseDate <= ?
                          AND Status <> 'Cancelled' AND ITCEligible = 1""", (start, end), one=True)

    upload = db.query("""SELECT * FROM Gstr2bUploads WHERE Period=? AND ParseStatus='Parsed'
                       ORDER BY UploadID DESC LIMIT 1""", (period,), one=True)

    itc_purchase = dict(cgst=round(purch_agg["cgst"], 2), sgst=round(purch_agg["sgst"], 2),
                         igst=round(purch_agg["igst"], 2))
    itc_purchase["total"] = round(itc_purchase["cgst"] + itc_purchase["sgst"] + itc_purchase["igst"], 2)

    itc_2b = None
    if upload:
        itc_2b = dict(cgst=round(upload["ITCCentral"], 2), sgst=round(upload["ITCState"], 2),
                      igst=round(upload["ITCIntegrated"], 2), cess=round(upload["ITCCess"], 2))
        itc_2b["total"] = round(itc_2b["cgst"] + itc_2b["sgst"] + itc_2b["igst"], 2)

    outward = dict(taxable=round(sales_agg["taxable"], 2), cgst=round(sales_agg["cgst"], 2),
                    sgst=round(sales_agg["sgst"], 2), igst=round(sales_agg["igst"], 2))
    outward["total_tax"] = round(outward["cgst"] + outward["sgst"] + outward["igst"], 2)

    itc_to_use = itc_2b if itc_2b else itc_purchase
    net_payable = dict(
        cgst=max(round(outward["cgst"] - itc_to_use["cgst"], 2), 0),
        sgst=max(round(outward["sgst"] - itc_to_use["sgst"], 2), 0),
        igst=max(round(outward["igst"] - itc_to_use["igst"], 2), 0),
    )
    net_payable["total"] = round(net_payable["cgst"] + net_payable["sgst"] + net_payable["igst"], 2)

    return dict(period=period, outward=outward, itc_purchase=itc_purchase, itc_2b=itc_2b,
                using_2b=bool(itc_2b), net_payable=net_payable, gstr2b_upload=upload)


# ---------------------------------------------------------------------
# GSTR-2B Excel upload parsing (defensive, header-name-driven)
# ---------------------------------------------------------------------

ITC_SHEET_CANDIDATES = ["b2b", "b2ba", "cdnr", "cdnra", "isd", "isda", "impg", "impgsez"]

HEADER_ALIASES = {
    "integrated_tax": ["integrated tax"],
    "central_tax": ["central tax"],
    "state_tax": ["state/ut tax", "state tax"],
    "cess": ["cess"],
    "itc_availability": ["itc availability", "eligibility for itc", "itc eligibility"],
}


def _find_header_row(ws, max_scan_rows=15):
    """Scans the first few rows of a sheet for one that looks like a
    column-header row (has both 'Integrated Tax' and 'Central Tax'
    somewhere in it) and returns (row_index, {alias_key: col_index})."""
    max_row = min(max_scan_rows, ws.max_row or 0)
    max_col = ws.max_column or 0
    for r in range(1, max_row + 1):
        values = {}
        for c in range(1, max_col + 1):
            v = ws.cell(row=r, column=c).value
            if isinstance(v, str) and v.strip():
                values[c] = v.strip().lower()
        if not values:
            continue
        found = {}
        for key, aliases in HEADER_ALIASES.items():
            for c, v in values.items():
                if any(a in v for a in aliases):
                    found[key] = c
                    break
        if "integrated_tax" in found and "central_tax" in found:
            return r, found
    return None, {}


def parse_gstr2b_excel(file_path):
    """Best-effort parser for a GSTR-2B Excel download. Returns a dict:
      {ok, message, itc_integrated, itc_central, itc_state, itc_cess, record_count}

    Scans every sheet whose name looks like a standard GSTR-2B
    invoice-level sheet (B2B, B2BA, CDNR, CDNRA, ISD, ISDA, IMPG,
    IMPGSEZ) for a header row containing 'Integrated Tax' / 'Central Tax'
    / 'State/UT Tax' / 'Cess' columns (by name, not fixed position), sums
    those columns for rows marked ITC-available, and skips rows explicitly
    marked not eligible.

    NOTE: this has not been verified against a real GSTN-issued GSTR-2B
    file in this environment (no sample was available to test against) -
    it's built from GSTN's publicly documented sheet layout. If your
    download's layout doesn't match, this fails loudly (ok=False) rather
    than showing a plausible-looking wrong number - please sanity-check
    the parsed totals against the 'Summary' sheet in your actual file the
    first time you use this.
    """
    try:
        import openpyxl
    except ImportError:
        return dict(ok=False, message="openpyxl is not installed on the server — ask for it to be added.",
                    itc_integrated=0, itc_central=0, itc_state=0, itc_cess=0, record_count=0)

    try:
        wb = openpyxl.load_workbook(file_path, data_only=True, read_only=True)
    except Exception as e:
        return dict(ok=False, message=f"Could not open this as an Excel (.xlsx) file: {e}",
                    itc_integrated=0, itc_central=0, itc_state=0, itc_cess=0, record_count=0)

    totals = dict(itc_integrated=0.0, itc_central=0.0, itc_state=0.0, itc_cess=0.0)
    record_count = 0
    sheets_used = []

    try:
        for sheet_name in wb.sheetnames:
            name_l = sheet_name.strip().lower().replace(" ", "").replace("-", "").replace("_", "")
            if not any(cand.replace("-", "") in name_l for cand in ITC_SHEET_CANDIDATES):
                continue
            ws = wb[sheet_name]
            header_row, cols = _find_header_row(ws)
            if not header_row:
                continue
            sheets_used.append(sheet_name)
            for r in range(header_row + 1, (ws.max_row or header_row) + 1):
                def cell(key):
                    c = cols.get(key)
                    return ws.cell(row=r, column=c).value if c else None

                igst, cgst, sgst, cess = cell("integrated_tax"), cell("central_tax"), cell("state_tax"), cell("cess")
                if not any(isinstance(v, (int, float)) for v in (igst, cgst, sgst, cess)):
                    continue  # blank/spacer/total row without numeric tax columns
                elig = cell("itc_availability")
                if isinstance(elig, str) and elig.strip() and elig.strip().lower() != "yes":
                    continue  # explicitly marked not eligible for ITC — excluded from the total
                try:
                    totals["itc_integrated"] += float(igst or 0)
                    totals["itc_central"] += float(cgst or 0)
                    totals["itc_state"] += float(sgst or 0)
                    totals["itc_cess"] += float(cess or 0)
                    record_count += 1
                except (TypeError, ValueError):
                    continue
    finally:
        wb.close()

    if not sheets_used:
        return dict(ok=False,
                    message="Couldn't find a recognizable B2B/CDNR/ISD/IMPG sheet with 'Integrated Tax' and "
                            "'Central Tax' columns in this file. This may not be a GSTR-2B download, or GSTN may "
                            "have changed the file layout since this was built — please check the file manually "
                            "and enter figures on the GSTR-3B page by hand if needed.",
                    itc_integrated=0, itc_central=0, itc_state=0, itc_cess=0, record_count=0)

    return dict(ok=True,
                message=f"Parsed {record_count} ITC-eligible record(s) from sheet(s): {', '.join(sheets_used)}. "
                        f"Please spot-check this total against the 'Summary' sheet in your downloaded file.",
                itc_integrated=round(totals["itc_integrated"], 2),
                itc_central=round(totals["itc_central"], 2),
                itc_state=round(totals["itc_state"], 2),
                itc_cess=round(totals["itc_cess"], 2),
                record_count=record_count)
